name: deploy_production

on:
    push:
        branches:
            - 'master'

jobs:
    deploy_production:
        uses: ./.github/workflows/linode-deployment.yml
        with:
            ENV_NAME: master
            WEB_SERVER_PATH: '~/webui-production/management-ui'
            PORT: '8000'
        secrets:
            LINODE_IP: ${{ secrets.LINODE_IP }}
            USER: ${{ secrets.USER }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
